laraveluk/website

resources/views/auth/login.blade.php, resources/views/auth/passwords/email.blade.php, resources/views/auth/passwords/reset.blade.php, resources/views/auth/register.blade.php
The old layout file (layouts.app) no longer exists, so I updated the frontend views to extend the new frontend layout file
=> amend master layout path in frontend views

app/Http/Kernel.php
=> Removed Passport Middleware

resources/views/frontend/master.blade.php
=> Fixed wrong path javascript

app/Http/Controllers/Ajax/PostController.php, routes/ajax.php
Add API routes and controller for administration of blog posts
=> add scaffolding for blog post CRUD (awaiting DB table and model)

.editorconfig
Add an editorconfig file to encourage consistent line endings and whitespace settings.
_Note this can't cover all PSR-2 rules such as line breaks after opening braces, but at least it handles tabs vs spaces and line endings_
=> add PSR-2 editorconfig file

resources/views/auth/login.blade.php, resources/views/auth/register.blade.php, resources/views/frontend/master.blade.php
Updated Login and register form designs
=> Login and register form updates

resources/views/auth/login.blade.php
Fixed csrf token error on login page
=> Fixed csrf token

app/Providers/RouteServiceProvider.php, routes/api.php
to remove authentication from deployment webhook
=> move web and auth middleware onto specific route group in api 

app/Http/Middleware/VerifyCsrfToken.php
Added deploy webhook url to csrf middleware exception
=> Middleware exception for deploy webhook

app/Http/Controllers/Auth/SlackLoginController.php, app/Http/Controllers/ProfileShowController.php, app/Models/Profile.php, app/Models/SocialLinks.php, app/Models/User.php, database/migrations/2018_02_04_183153_add_slack_fields_to_user_table.php, database/migrations/2018_02_04_191245_create_profiles_table.php, database/migrations/2018_02_04_192742_create_social_links_table.php, resources/views/frontend/profile.blade.php, routes/web.php
couple of slack fields get pulled into user table when logging in with slack.
profile / social_links tables migrations models, single use controller for profile view and profile data brought into blade ready for vue goodness / ajax middleware routes
spending some time with tailwind through the week ..
=> pull in slack avatar and nickname, profile migrations models controller, view

app/Http/Controllers/Blog/CommentController.php, app/Models/Comment.php, app/Models/Post.php, database/migrations/2018_02_04_204455_create_comments_table.php, resources/views/frontend/posts/show.blade.php, routes/web.php
This adds commenting ability to the Front End Blog.
=> Add Blog Comments to Blog Front End

app/Http/Controllers/Auth/RegisterController.php, resources/views/auth/login.blade.php, resources/views/auth/register.blade.php
Added validation messages to login and register form
=> Validation messages for login and register form

resources/assets/js/backend/app/blog/components/PostCreate.vue
Add Interview Post Type to back end blog creation form.
=> Add Interview Post Type

app/Http/Controllers/Api/UtilController.php, deploy.sh
Arguments passed into deploy script to distinguish between requests and cron
=> Pass arguments into deploy script

resources/views/frontend/posts/show.blade.php
This PR stops guests from being able to leave comments.
=> Fix guest commenting being broken

deploy
Renamed deploy script and fixed syntax for bourne shell
=> Deploy script fix

deploy
=> Change shell to bash

deploy
Don't yarn if request from github webhook
=> Don't yarn if request from github webhook

app/Http/Controllers/Api/UtilController.php
Fixed Bug in Controller's Process command
=> Fixed command in UtilController

app/Http/Controllers/Api/UtilController.php
Pass argument with webhook request to exlude npm compilation
=> Webhook request to exlude npm compilation

deploy, resources/views/frontend/laravel_people.blade.php
Add margin between each Laravel celeb containers
=> Add margin between each Laravel celeb containers

resources/assets/js/backend/app/blog/components/PostShow.vue
Add line height to blog post body
=> Blog post body line height

app/Http/Controllers/Auth/RegisterController.php, app/Models/Role.php, app/Models/User.php, app/Policies/PostPolicy.php, app/Providers/AuthServiceProvider.php, database/migrations/2018_02_08_221421_create_roles_table.php, database/migrations/2018_02_08_221628_role_user.php, database/migrations/2018_02_08_224146_add_location_to_user_table.php, resources/views/frontend/posts/show.blade.php
This PR creates a Policy to prevent users who did not create a post from editing or deleting it.
Implemented member role logic. Users are assigned 'Member' role on registration
Added a Migration to create location column in users table. This migration did not run after it was previously created.
=> Policy Implementation for Posts

resources/assets/js/backend/app/blog/components/PostCreate.vue, resources/assets/js/backend/backend.js, resources/assets/js/backend/components/App.vue, resources/assets/js/components/SiteFooter.vue, resources/assets/sass/app.scss, resources/assets/sass/components/_forms.scss
I have enhanced the create post form and extracted some styles to a form component to use throughout the site.
I have also added little visual update and information as well as visual validation. The submit button is disabled until the form is completed, so ensuring a user adds at least one tag for now. This also resolves #86 with regards to the select drop down.
[A Visual Image of changes can be viewed here](https://i.imgur.com/ttsVAZl.png)
Added footer VueJS components to add and enable a gap in the footer, this can be used to add legal and other details at later date.
=> Update the post form visually and add a little validation

app/Http/Controllers/Api/PostController.php, resources/assets/js/backend/app/blog/components/PostCreate.vue
Hey guys,
I wanted to help out a bit but didn't have a huge amount of time.
Let me know if I've completely missed the point!
=> Optional tags when creating a blog post

resources/assets/js/components/Navbar.vue, resources/views/auth/login.blade.php, resources/views/auth/register.blade.php
Add message on login and signup pages to request users log out of other slack teams to avoid Slack invalid_team_for_non_distributed_app error
Removed Slackm buttons on the Nav page and replace with Signup link
=> Login/Signup Page 

package.json, resources/assets/js/backend/app/blog/components/PostCreate.vue, resources/assets/js/backend/app/blog/components/PostShow.vue, resources/assets/js/backend/app/blog/components/index.js, yarn.lock
Replaced vue-wysiwyg with vue-2-editor
=> Post Editor Replacement

resources/views/frontend/laravel_people.blade.php
(per request from Barry)
HEY UK FRIENDS 👋  <3
=> Add Matt Stauffer

resources/assets/js/backend/app/blog/components/PostEdit.vue, resources/assets/js/backend/app/blog/components/index.js, resources/assets/js/backend/app/blog/index.js, resources/assets/js/backend/app/blog/routes/index.js, resources/views/frontend/posts/show.blade.php
Users will now link directly to edit form from the frontend edit button click
Minor style changes
=> Edit Post User Journey

resources/views/frontend/index.blade.php
Fixed homepage rendering for mobile
=> Homepage mobile rendering

app/Enums/ProfileKeys.php, app/Http/Controllers/Api/ProfileController.php, app/Models/Profile.php, app/Models/ProfileKey.php, app/Models/User.php, database/migrations/2018_03_04_133849_create_profile_keys_table.php, database/migrations/2018_03_04_133955_remove_profiles_columns_and_add_key_pairs.php, database/seeds/ProfileKeysTableSeeder.php, routes/api.php
Hey guys,
Hopefully this is good.
It uses a key/value pairs to build a list of profile attributes rather than just static columns that we can't build on.
I also provided enums so that we can decide on the 'type' for the field in the front end. If this needs changing let me know.
You can get/post profile/{user_id} to show/update the keypairs, it will loop through the form and try to apply any of the allowed keys from the profile_keys table.
Lee
=> Profile Crud, key/value, migration, seeder, enums, relations, controller

resources/assets/js/components/Navbar.vue, resources/views/frontend/about.blade.php
CSS Changes to About us page
Added About us to the Nav links
Removed Blog dropdown - no longer needed
=> Add About us link to Navbar

resources/views/frontend/index.blade.php
Added Snapshooter as sponsor on the homepage.
=> Added Sponsors section on the homepage

resources/views/frontend/index.blade.php
Add the link to https://snapshooter.io as missing
=> Add missing sponsor link

app/Http/Controllers/Auth/RegisterController.php, app/Models/User.php, composer.json
Hey, 
Make sure you run a composer install so that the unirest package is loaded in :)
User registration to the site now auto invites them to our Slack channel.
Thanks.
=> Added Slack Invite on registration. Also added Unirest for requests

app/Models/User.php, config/slack.php
Shouldn't need anything special, just deploy!
=> Slack config file created and updated in User Model

resources/views/frontend/home/partials/latest-posts.blade.php
Since my latest PR has been merged in the homepage of laravekphp.uk has been down.
I think this may fix but I can't be certain.
Paging @stevepop
=> Potential fix for homepage

resources/views/frontend/home/partials/latest-interviews.blade.php, resources/views/frontend/home/partials/latest-resources.blade.php
This pull request adjusts the alignment of the homepage partials content to make it look more natural.
=> Adjust the alignment of homepage partials content.

resources/views/frontend/home/partials/latest-interviews.blade.php, resources/views/frontend/home/partials/latest-posts.blade.php, resources/views/frontend/home/partials/latest-resources.blade.php
This pull request increases the width of the posts partial on the homepage to 1/2 and decreases the width of the other two to 1/4.
=> Increase width of posts partial on the homepage.

resources/views/frontend/home/partials/hero.blade.php, tailwind.js
This pull request introduces more accurate margins for hero content, meaning that it looks better and more naturally centred across all devices.
=> Improved the accuracy of hero content margins.

resources/views/frontend/home/partials/latest-posts.blade.php
This pull request fixes an issue that resulted in tags not showing inline.
=> Tags now show inline (latest posts homepage partial)

app/Http/Controllers/Api/Frontend/PostsController.php, app/Http/Controllers/Blog/PostController.php, package.json, resources/assets/js/components/blog/PostItem.vue, resources/assets/js/components/blog/PostLists.vue, resources/assets/js/frontend/app.js, resources/views/frontend/home/partials/introduction.blade.php, resources/views/frontend/posts/index.blade.php, routes/api.php, tests/Feature/ViewPostsTest.php, yarn.lock
- Migrated posts in blade template to Vue.js to better manage the rendering
- Implemented new end-point for fetching posts in PostList component
- Implemented a PostItem component to render individual posts
- Removed logic for fetching posts from the Post Controller loading the blade template
- Changed News event type display to POST as displaying it as News is quite confusing since these are individual posts and not announcements.
=> Moved Posts from Blade template To Vuejs

resources/assets/js/components/blog/PostItem.vue
=> Fixed Blog title links

package.json, yarn.lock
Ran Npm audit and updated packages with vulnerabilities.
=> Removed all npm vulnerabilities

resources/assets/js/components/blog/PostItem.vue
Fix wrong Post dates
Reverted upgrade of lodash due to Prettier errors
=> Fix wrong Post dates

.travis.yml, app/Http/Controllers/Api/Frontend/PostsController.php, app/Http/Controllers/Api/PostController.php, app/Http/Controllers/Blog/PostController.php, resources/assets/js/components/blog/PostLists.vue
This commit fixes the order of posts, displaying recent posts first.
=> Fixed Order of Posts

resources/assets/js/backend/app/blog/components/PostEdit.vue, resources/assets/js/backend/components/App.vue
Fixed some layout issues on the Post edit form page
=>  Edit Post form

resources/views/auth/login.blade.php
=> Fixes #160

app/Helpers/TwitterImage.php, resources/views/frontend/laravel_people.blade.php
Fetches the specified twitter user's profile image by capturing the redirect URL of https://twitter.com/username/profile_image?size=original 
It stores URL in cache for 4 days.
=> Fix broken twitter images, fetch and cache URLs.

resources/views/frontend/home/index.blade.php, resources/views/frontend/home/partials/hero.blade.php
**I don't want a lot for Christmas**
There's just one thing I need
**I don't care about presents**
Underneath the Christmas tree
**I just want you for my own**
More than you could ever know
**Make my wish come true**
All I want for Christmas is you.
MERRY CHRISTMAS STEVE !
=> festive changes

resources/views/frontend/home/index.blade.php, resources/views/frontend/home/partials/hero.blade.php
I made a mistake in the elf factory and the snow machine went NUTS! so i went back and fixed
=> The top Elf dan fixed the snow machine

resources/assets/sass/components/_homepage.scss
this should now resolve snow problem if not i will quit my life lol
=> fixed css issue i accidently done

resources/assets/sass/components/_homepage.scss, resources/views/frontend/home/partials/hero.blade.php
hopefully this will improve site performance if not will scrap snow effect
=> replaced with better snow to see if speeds up site in production

package-lock.json, package.json
=> Update vue and package-lock to remove vulnerable event-stream

app/Events/EventHasNewSignup.php, app/Http/Controllers/Page/EventController.php, app/Listeners/NotifyWhenEventUserSignedUp.php, app/Models/EventSignup.php, app/Models/ProfileKey.php, app/Notifications/NotifyNewUserSignup.php, app/Providers/EventServiceProvider.php, config/services.php, package-lock.json, resources/views/email/event_signup.blade.php
Logic for the integration of Email and Slack notification.
=> Mail and Slack Integeration

app/Notifications/NotifyNewUserSignup.php
Fix wrong 'From' email address in Notification
=> Correct domain name in email address

app/Http/Controllers/Page/EventController.php, resources/assets/sass/event.scss, resources/views/pages/event.blade.php
must run `npm run production` for the style changes
=> changes added

app/Console/Commands/SendEventInfo.php, app/Notifications/EventUpdate.php, resources/views/email/event_info.blade.php
Added command to send event info to contacts from other sources
=> Event Info Dispatch

app/Notifications/NotifyNewUserSignup.php
Change slack notification channel to event-rsvp
=> Slack notification channel change

app/Console/Commands/SendEventInfo.php, resources/views/email/event_info.blade.php
event Email with Eventbrite  link
=> Email Event details

package.json, resources/views/frontend/slack.blade.php
Updated axios to latest version
Temporarily commented out Slack join page
=> Update to Axios and disabled Join form

app/Helpers/Slack.php
Temporarily disallow slack invitations to stop the influx of spambots.
=> Disallow Slack Invitations

resources/views/pages/event.blade.php
=> Update Speaker details
